newsaggregator/urls.py
from django.conf.urls.defaults import *
from newsaggregator.models import Entry
from newsaggregator.feeds import RssFeed, AtomFeed
from newsaggregator import settings

feeds = { 
    'rss': RssFeed,
    'atom': AtomFeed,
}

entry_dict = {
    'queryset': Entry.published_objects.all(),
    'date_field': 'pub_date',
}

entry_dict_detail = {
    'queryset': Entry.published_objects.all(),
    'date_field': 'pub_date',
}

entry_dict_year = {
    'queryset': Entry.published_objects.all(),
    'date_field': 'pub_date',
    'make_object_list': 'True',
}

urlpatterns = patterns('',
    (r'^rss/$', 'django.contrib.syndication.views.feed', {'feed_dict': feeds, 'url': 'rss'}),
    (r'^atom/$', 'django.contrib.syndication.views.feed', {'feed_dict': feeds, 'url': 'atom'}),
)

if settings.STATE_DEFAULT != settings.STATE_PUBLISHED:
    urlpatterns += patterns('django.views.generic.create_update',
        (r'^create/$', 'create_object', dict(model=Entry, login_required=True, post_save_redirect='/news/posted/', extra_context={'STATE_DEFAULT': settings.STATE_DEFAULT}), "newsaggregator_create"),
    )
else:
    urlpatterns += patterns('django.views.generic.create_update',
        (r'^create/$', 'create_object', dict(model=Entry, login_required=True, extra_context={'STATE_DEFAULT': settings.STATE_DEFAULT}), "newsaggregator_create"),
    )

urlpatterns += patterns('django.views.generic.date_based',
    (r'^(?P<year>\d{4})/(?P<month>[a-z]{3})/(?P<day>\w{1,2})/(?P<slug>[0-9A-Za-z-]+)/$', 'object_detail', dict(entry_dict_detail, slug_field='slug')),
    (r'^$', 'archive_index', entry_dict, "newsaggregator_main"),
    (r'^(?P<year>\d{4})/$', 'archive_year',  entry_dict_year),
    (r'^(?P<year>\d{4})/(?P<month>[a-z]{3})/(?P<day>\w{1,2})/$',  'archive_day', entry_dict),
    (r'^(?P<year>\d{4})/(?P<month>[a-z]{3})/$',  'archive_month', entry_dict),
)

urlpatterns += patterns('django.views.generic.simple',
    (r'^posted/$', 'direct_to_template', dict(template='newsaggregator/posted.html')),
)

newsaggregator/models.py
from django.contrib.auth.models import User
from django.db import models
from newsaggregator import settings
from tagging.fields import TagField
from published_manager.managers import PublishedManager
from django.utils.translation import ugettext as _

class Feed(models.Model):
    title = models.CharField(_("Title"), max_length=200)
    tagline = models.TextField(_('Tagline'), blank=True)
    feed_url = models.URLField(_("Feed Url"), unique=True)
    public_url = models.URLField()
    is_defunct = models.BooleanField()
    tagline = models.TextField(_("Tagline"), blank=True)
    link = models.URLField(_("Link"), blank=True)
    etag = models.CharField(_("Etag"), max_length=50, blank=True)
    mod_date = models.DateTimeField(_("Date Modified"), null=True, blank=True)
    check_date = models.DateTimeField(_("Date Checked"), null=True, blank=True)

    class Admin:
        pass

    def __unicode__(self):
        return _(self.title)

class Entry(models.Model):
    """
    A news entry 
    """
    feed = models.ForeignKey(Feed, null=True, blank=True, verbose_name=_("Source Feed"))
    link = models.URLField(null=True, blank=True, verbose_name=_("Source Link"))
    summary = models.TextField(null=True, blank=True, verbose_name=_("Summary"))
    mod_date = models.DateTimeField(verbose_name=_("Date Modified"), null=True, blank=True, auto_now=True)
    guid = models.CharField(max_length=200, db_index=True, verbose_name=_("Globally Unique Identifier"), blank=True, null=True)
    author = models.CharField(_("Author"), max_length=50, null=True, blank=True)
    author_email = models.EmailField(_("Author's Email"), null=True, blank=True)
    comments = models.URLField(_("Comments"), null=True, blank=True)
    title = models.CharField(max_length=255, verbose_name=_("Title"))
    slug = models.SlugField(prepopulate_from=('title',), unique=True, verbose_name=_("Slug Field"), blank=True, null=True)
    content = models.TextField(blank=True, verbose_name=_("Content"))
    pub_date = models.DateTimeField(auto_now_add=True, verbose_name=_("Date Published"))
    user = models.ForeignKey(User, verbose_name=_("User"), null=True, blank=True)
    state = models.CharField(max_length=1, choices=settings.STATE_CHOICES, default=settings.STATE_DEFAULT, verbose_name=_("State of object"))
    ip_address = models.IPAddressField(verbose_name=_("Author's IP Address"), null=True, blank=True)
    tags = TagField(help_text=_("Enter key terms seperated with a space that you want to associate with this Entry"), verbose_name=_("Tags"))
    objects = models.Manager()
    published_objects = PublishedManager()

    def get_absolute_url(self):
        if self.link:
            return self.link
        else:
            return "/news/%s/%s/" % (self.pub_date.strftime("%Y/%b/%d").lower(), self.slug)

    def get_author_str(self):
        if self.user:
            return "<a href=%s>%s</a>" % (self.user.get_absolute_url(), self.user)
        elif self.author:
            if self.author_email:
                if not self.author_email == "nospam@nospam.com":
                    return "<a href=mailto:%s>%s</a>" % (self.author_email, self.author)
                else:
                    return self.author
            else:
                return self.author
        else:
            return ''

    def __unicode__(self):
        return _(self.title)

    class Meta:
        ordering = ['pub_date']
        get_latest_by = "pub_date"
        verbose_name = _("Entry")
        verbose_name_plural = _("Entries")

    class Admin:
        date_hierarchy = 'pub_date'
        list_display = ('title', 'user')
        ordering = ['pub_date']
        search_fields = ['title']

newsaggregator/templates/newsaggregator/_entry.html
{% load i18n %}
<a id="{{ object.slug }}" href="{{ object.get_absolute_url }}">{% blocktrans with object|title as object_title %}{{ object_title }}{% endblocktrans %}</a><br />
{% if object.ip_address %}
{% load iptocountry_flag %}{% get_flag object.ip_address as flag %}<img src="{{ flag.flag_url }}" alt="{{ flag.COUNTRY_NAME|lower }}" />
{% endif %}
{% blocktrans with object.description as object_description %}{{ object_description }}{% endblocktrans %}<br />
{% trans "Posted on" %} {{ object.pub_date|date:"F j, Y" }} {% trans "by" %} {% autoescape off %}{{ object.get_author_str }}{% endautoescape %}<br />
{% load comments %}
{% get_comment_count for newsaggregator.entry object.id as comment_count %}
Comment{{ comment_count|pluralize }}: {{ comment_count }}<br />

newsaggregator/templates/newsaggregator/entry_archive.html
{% extends "base.html" %}
{% load i18n %}
{% block title %}{% trans "Entries" %}{% endblock %}
{% block breadcrumb %}<li class="last">{% trans "Entries" %}</li>{% endblock %}
{% block content %}
{% for object in latest %}
{% include "newsaggregator/_entry.html" %}
{% endfor %}
{% endblock %}

newsaggregator/templates/newsaggregator/entry_archive_day.html
{% extends "base.html" %}
{% load i18n %}
{% block title %}{% trans "Entries" %} {{ day|date:"Y" }} {{ day|date:"F" }} {{ day|date:"d" }}{% endblock %}
{% block breadcrumb%}<li><a href="/news/">{% trans "Entries" %}</a></li> <li><a href="/news/{{ day|date:"Y"|lower }}/">{{ day|date:"Y"|lower }}</a></li> <li><a href="/news/{{ day|date:"Y"|lower }}/{{ day|date:"F" }}/">{{ day|date:"F" }}</a></li> <li class="last">{{ day|date:"d" }}</li>{% endblock %}
{% block content %}
{% for object in object_list %}
{% include "newsaggregator/_entry.html" %}
{% endfor %}
{% endblock %}

newsaggregator/templates/newsaggregator/entry_archive_month.html
{% extends "base.html" %}
{% load i18n %}
{% block title %}{% trans "Entries" %} {{ month|date:"Y" }} {{ month|date:"F" }}{% endblock %}
{% block breadcrumb%}<li><a href="/news/">{% trans "Entries" %}</a></li> <li><a href="/news/{{ month|date:"Y"|lower }}/">{{ month|date:"Y"|lower }}</a></li> <li class="last">{{ month|date:"F" }}</li>{% endblock %}
{% block content %}
{% for object in object_list %}
{% include "newsaggregator/_entry.html" %}
{% endfor %}
{% endblock %}

newsaggregator/templates/newsaggregator/entry_archive_year.html
{% extends "base.html" %}
{% load i18n %}
{% block title %}{% trans "Entry" %} {{ year }}{% endblock %}
{% block breadcrumb%}<li><a href="/news/">{% trans "Entries" %}</a></li> <li class="last">{{ year }}</li>{% endblock %}
{% block content %}
{% for object in object_list %}
{% include "newsaggregator/_entry.html" %}
{% endfor %}
{% endblock %}

newsaggregator/templates/newsaggregator/entry_detail.html
{% extends "base.html" %}
{% load i18n %}
{% load comments %}
{% block title %}{% trans "Entries" %} {% blocktrans with object|title as object_title %}{{ object_title }}{% endblocktrans %}{% endblock %}
{% block breadcrumb%}<li><a href="/news/">{% trans "Entries" %}</a></li> <li><a href="/news/{{ object.pub_date|date:"Y"|lower }}/">{{ object.pub_date|date:"Y"|lower }}</a></li> <li><a href="/news/{{ object.pub_date|date:"Y"|lower }}/{{ object.pub_date|date:"b"|lower }}/">{{ object.pub_date|date:"F" }}</a></li> <li class="last">{% blocktrans with object|title as object_title %}{{ object_title }}{% endblocktrans %}</li>{% endblock %}
{% block content %}
{% include "newsaggregator/_entry.html" %}
{% get_comment_list for newsaggregator.entry object.id as comment_list %}
{% for comment in comment_list %}
{% include "comments/_comment.html" %}
{% endfor %}
{% blocktrans %}Post a comment{% endblocktrans %}
{% comment_form for newsaggregator.entry object.id %}
{% endblock %}

newsaggregator/templates/newsaggregator/entry_form.html
{% extends "base.html" %}
{% load i18n %}
{% block title %}{% trans "News Create" %}{% endblock %}
{% block extrahead %}
{% load adminmedia %}<script type="text/javascript" src="{% admin_media_prefix %}js/urlify.js"></script>
{% endblock %}
{% block breadcrumb%}<li><a href="/news/">{% trans "News" %}</a></li> <li class="last">{% trans "Create" %}</li>{% endblock %}
{% block content %}
<form method="post" >
{% if form.has_errors %}
<h2>{% blocktrans %}Please correct the following error{{ form.error_dict|pluralize }}{% endblocktrans %}:</h2>
{% endif %}
<input type="hidden" id="id_user" name="user" value="{{ user.id }}" />
<input type="hidden" id="id_state" name="state" value="{{ STATE_DEFAULT }}" />
<input type="hidden" id="id_slug" name="slug" value="" maxlength="50" />
<input type="hidden" id="id_ip_address" class="vIPAddressField required" name="ip_address" size="15" value="{{ request.META.REMOTE_ADDR }}" maxlength="15" />
{% if form.title.errors %}*** {% blocktrans %}{{ form.title.errors|join:", " }}{% endblocktrans %}{% endif %}
<label for"id_title">{% trans "Title" %}:</label> {{ form.title }}
{% if form.content.errors %}*** {% blocktrans %}{{ form.content.errors|join:", " }}{% endblocktrans %}{% endif %}
<label for"id_content">{% trans "Content" %}:</label> {{ form.content }}
{% if form.tags.errors %}*** {% blocktrans %}{{ form.tags.errors|join:", " }}{% endblocktrans %}{% endif %}
<label for"id_tags">{% trans "Tags" %}:</label> {{ form.tags }}
<input type="submit" value="{% blocktrans %}Create{% endblocktrans %}" />
</form>
<script type="text/javascript">
        document.getElementById("id_slug").onchange = function() { this._changed = true; };document.getElementById("id_title").onkeyup = function() { var e = document.getElementById("id_slug"); if(!e._changed) { e.value = URLify(document.getElementById("id_title").value, 50);} }; 
</script>
{% endblock %}

newsaggregator/templates/newsaggregator/posted.html
{% extends "base.html" %}
{% block title %}News - Posted{% endblock %}
{% block breadcrumb %}<li>News</li> <li class="last">Posted</li>{% endblock %}
{% block content %}
<h1>News entry posted successfully</h1>

<p>Thanks for contributing. Your entry is being reviewed.</p>
{% endblock %}